# Generated by Django 5.2.7 on 2025-11-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScritturaContabile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descrizione', models.CharField(max_length=255)),
                ('dare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avere', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
