# Generated by Django 5.2.7 on 2025-11-03 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SezioneBilancio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sezioni di bilancio',
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaBilancio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('sezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='bilancio.sezionebilancio')),
            ],
            options={
                'verbose_name_plural': 'Categorie di bilancio',
                'ordering': ['sezione__codice', 'codice'],
                'unique_together': {('sezione', 'codice')},
            },
        ),
        migrations.CreateModel(
            name='SottocategoriaBilancio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sottocategorie', to='bilancio.categoriabilancio')),
            ],
            options={
                'verbose_name_plural': 'Sottocategorie di bilancio',
                'ordering': ['categoria__codice', 'codice'],
                'unique_together': {('categoria', 'codice')},
            },
        ),
        migrations.CreateModel(
            name='VoceBilancio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('natura_conto', models.CharField(blank=True, choices=[('DARE', 'Dare'), ('AVERE', 'Avere')], max_length=10, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sottocategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci', to='bilancio.sottocategoriabilancio')),
            ],
            options={
                'verbose_name_plural': 'Voci di bilancio',
                'ordering': ['sottocategoria__codice', 'codice'],
                'unique_together': {('sottocategoria', 'codice')},
            },
        ),
    ]
